# AUTHOR: Daniel Kraus - dankraus@cisco.com
version: "2"
services:
  influxdb:
    container_name: influxdb
    image: influxdb:latest
    ports:
      - "8083:8083"
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=password
      - DOCKER_INFLUXDB_INIT_ORG=Cisco
      - DOCKER_INFLUXDB_INIT_BUCKET=telemetry
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=Cisco!123
    volumes:
      - ./vols/:/var/lib/influxdb
    restart: always

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    links:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=password
    volumes:
      - ./grafana/grafana-provisioning:/etc/grafana/provisioning
    restart: always

  telegraf:
    container_name: telegraf
    image: telegraf:latest 
    ports:
      - "57000:57000"
      - "57001:57001"
    environment:
      - INFLUXDB_TOKEN=Cisco!123
    links:
      - influxdb
    volumes:
      - ./conf/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
