# AUTHOR: Daniel Kraus - dankraus@cisco.com
apiVersion: 1

datasources:
  - name: InfluxDB_v2_InfluxQL
    type: influxdb
    access: proxy
    url: http://10.48.188.61:8086
    jsonData:
      dbName: telemetry
      httpMode: GET
      httpHeaderName1: 'Authorization'
    secureJsonData:
      httpHeaderValue1: 'Token Cisco!123'
